export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_PRODUCTS = "SORT_PRODUCTS";